dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main_app.urls'))
]

main_app/urls.py
from unicodedata import name
from django.urls import path
from . import views

urlpatterns=[
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('dogs/',views.index,name='index'),
    path('dogs/<int:dog_id>/',views.detail,name='detail'),
    path('dogs/create',views.DogCreate.as_view(),name='dogs_create'),
    path('dogs/<int:pk>/update/',views.DogUpdate.as_view(),name='dogs_update'),
    path('dogs/<int:pk>/delete/',views.DogDelete.as_view(),name='dogs_delete'),
    path('dogs/<int:dog_id>/add_price',views.add_price,name='add_price'),
    path('sports/',views.SportList.as_view(),name='sports_index'),
    path('sports/<int:pk>/',views.SportDetail.as_view(),name='sports_detail'),
    path('sports/create/', views.SportCreate.as_view(), name='sports_create'),
    path('sports/<int:pk>/update/', views.SportUpdate.as_view(), name='sports_update'),
    path('sports/<int:pk>/delete/', views.SportDelete.as_view(), name='sports_delete'),
    path('dogs/<int:dog_id>/assoc_sport/<int:sport_id>/', views.assoc_sport, name='assoc_sport'),
]

main_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Sport(models.Model):
    name= models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('sports_detail', kwargs={'pk': self.id})


class Dog(models.Model):
    name=models.CharField(max_length=100)
    breed=models.CharField(max_length=100)
    description=models.CharField(max_length=250)
    age=models.IntegerField()

    sports=models.ManyToManyField(Sport)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail',kwargs={'dog_id':self.id})    




class Bid(models.Model):
    customer=models.CharField(max_length=100)
    price=models.IntegerField()
    date=models.DateField('bidding date')

    dog=models.ForeignKey(Dog,on_delete=models.CASCADE)

    class Meta:
      ordering = ['-date']

    def __str__(self):
        return f"{self.customer} bid {self.price} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Bid

class BidForm(ModelForm):
    class Meta:
       model=Bid
       fields=['customer','date','price']

main_app/views.py
import imp
from django.shortcuts import redirect, render
from .models import Dog, Sport
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic import ListView,DetailView
from .forms import BidForm

# Create your views here.
# Define the home view
def home(request):
  return render(request,'home.html')

def about(request):
    return render(request,'about.html')

def index(request):
    dogs=Dog.objects.all()
    return render(request,'dogs/index.html',{'dogs': dogs })

def detail(request,dog_id):
    dog= Dog.objects.get(id=dog_id)
    id_list = dog.sports.all().values_list('id')
    sports_dog_doesnt_have= Sport.objects.exclude(id__in=id_list)
    bid_form=BidForm()
    return render(request,'dogs/detail.html',{'dog':dog,'bid_form':bid_form,'sports': sports_dog_doesnt_have})

def assoc_sport(request, dog_id, sport_id):
  # Note that you can pass a sport's id instead of the whole sport object
  Dog.objects.get(id=dog_id).sports.add(sport_id)
  return redirect('detail', dog_id=dog_id)    

class DogCreate(CreateView):
    model=Dog
    fields='__all__'
    # success_url='/dogs/'

class DogUpdate(UpdateView):
    model=Dog
    fields=['breed','description','age']

class DogDelete(DeleteView):
    model=Dog
    success_url='/dogs/' 

def add_price(request,dog_id):
    form=BidForm(request.POST)
    if form.is_valid():
        new_price=form.save(commit=False)
        new_price.dog_id=dog_id
        new_price.save()
    return redirect('detail',dog_id=dog_id)   

class SportList(ListView):
    model=Sport     

class SportDetail(DetailView):
    model=Sport    

class SportCreate(CreateView):
    model=Sport
    fields='__all__'

class SportUpdate(UpdateView):
    model=Sport
    fields=['name']

class SportDelete(DeleteView):
    model=Sport
    success_url='/sports/' 

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Dog Collector</h1>
<hr />
<p>Hire the Dog Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Dog Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{%url 'home'%}" class="left brand-logo">&nbsp;&nbsp;DogCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{%url 'about'%}">About</a></li>
          <li><a href="{%url 'sports_create'%}">Add Sport</a></li>
          <li><a href="{%url 'sports_index'%}">View All Sports</a></li>
          <li><a href="{%url 'dogs_create'%}">Add Dog</a></li>
          <li><a href="{%url 'index'%} ">View All Dogs</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Dog Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog Details</h1>

<div class="row">
    <div class="col s6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{{ dog.name }}</span>
          <p>Breed: {{ dog.breed }}</p>
          <p>Description: {{ dog.description|linebreaks }}</p>
          {% if dog.age > 0 %}
            <p>Age: {{ dog.age }}</p>
          {% else %}
            <p>Age: Kitten</p>
          {% endif %}
        </div>
        <div class="card-action">
          <a href="{% url 'dogs_update' dog.id %}">Edit</a>
          <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
        </div>
      </div>
    </div>
    <div class="col s6">
        <form action="{%url 'add_price' dog.id%}" method="POST">
            {% csrf_token %}
            {{ bid_form.as_p }}
            <input type="submit" class="btn" value="Bid">
          </form>
      <table class="striped">
        <thead>
          <tr><th>Customer</th><th>Price</th><th>Date</th></tr>
        </thead>
        <tbody>
          {% for bid in dog.bid_set.all %}
            <tr>
              <td>{{bid.customer}}</td>
              <td>{{bid.price}}</td>
              <td>{{bid.date}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>


  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ dog.name }}'s Sports</h3>
      {% if dog.sports.count %}
        {% for sport in dog.sports.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
              </span>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No sports :(</h5>
      {% endif %}
    </div>


    <div class="col s6">
        <h3>Available Sports</h3>
        {% if sports.count %}
          {% for sport in sports.all %}
            <div class="card">
              <div class="card-content">
                <span class="card-title"></span>
              </div>
              <div class="card-action">
                <form action="{% url 'assoc_sport' dog.id sport.id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn">Add</button>
                </form>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <h5>{{dog.name}} Already Has All sports Available</h5>
        {% endif %}
      </div>
    
  <script>
const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %} {% block content %}

<h1>Dog List</h1>

{%for dog in dogs %}
<div class="card">
  <a href="{%url 'detail' dog.id%}">
    <div class="card-content">
      <span class="card-title">{{ dog.name }}</span>
      <p>Breed: {{ dog.breed }}</p>
      <p>Description: {{ dog.description }}</p>
      {% if dog.age > 0 %}
      <p>Age: {{ dog.age }}</p>
      {% else %}
      <p>Age: Puppy</p>
      {% endif %}
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Dog</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' dog.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/dog_form.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Dog</h1>
{% endif %}

<form action="" method="POST">
 <!-- Django requires the following for security purposes -->    
{%csrf_token%}
<table>
    {{form.as_table}}
</table>
<input type="submit" value="Submit!" class="btn">

</form>


{% endblock %}

main_app/templates/main_app/sport_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Sport</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'sports_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/sport_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Sport Detail</h1>
<div class="row">
    <div class="col s6 col-offset-3">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{{ sport.name }}</span>
        </div>
        <div class="card-action">
          <a href="{% url 'sports_update' sport.id %}">Edit</a>
          <a href="{% url 'sports_delete' sport.id %}">Delete</a>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

main_app/templates/main_app/sport_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Sport</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/sport_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Sport List</h1>

{% for sport in sport_list %}
  <a href="{% url 'sports_detail' sport.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ sport.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}